Comment out self hosted build

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,48 +13,48 @@ on:
   schedule:
     - cron: '30 0 * * *'
 jobs:
-  build_self_hosted:
-    runs-on: self-hosted
-    steps:
-    - name: 'Cleanup build folder'
-      run: |
-        ls -la ./
-        sudo rm -rf ./* || true
-        sudo rm -rf ./.??* || true
-        ls -la ./
-    - uses: actions/checkout@v4
-    - name: Update apt-get
-      run: sudo apt-get update
-    - name: Install deps
-      run: sudo apt-get -y install coreutils quilt parted kpartx qemu-utils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc
-    - run: mkdir .ccache
-    - name: "Set up ccache cache"
-      uses: actions/cache@v4
-      with:
-        path: .ccache
-        key: ccache-${{ github.head_ref }}-${{ github.run_number }}
-        restore-keys: |
-          ccache-${{ github.head_ref }}
-          ccache
-    - run: ls -lah .ccache
-    - name: Build
-      run: sudo ./build.sh
-    - uses: actions/upload-artifact@v4
-      with:
-        name: debs
-        path: deploy/*.deb
-    - uses: actions/upload-artifact@v4
-      with:
-        name: images
-        path: deploy/*.zip
-    - uses: actions/upload-artifact@v4
-      with:
-        name: packages-info
-        path: deploy/*.info
-    - uses: actions/upload-artifact@v4
-      with:
-        name: mixxx-version
-        path: deploy/*.version
+  # build_self_hosted:
+  #   runs-on: self-hosted
+  #   steps:
+  #   - name: 'Cleanup build folder'
+  #     run: |
+  #       ls -la ./
+  #       sudo rm -rf ./* || true
+  #       sudo rm -rf ./.??* || true
+  #       ls -la ./
+  #   - uses: actions/checkout@v4
+  #   - name: Update apt-get
+  #     run: sudo apt-get update
+  #   - name: Install deps
+  #     run: sudo apt-get -y install coreutils quilt parted kpartx qemu-utils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc
+  #   - run: mkdir .ccache
+  #   - name: "Set up ccache cache"
+  #     uses: actions/cache@v4
+  #     with:
+  #       path: .ccache
+  #       key: ccache-${{ github.head_ref }}-${{ github.run_number }}
+  #       restore-keys: |
+  #         ccache-${{ github.head_ref }}
+  #         ccache
+  #   - run: ls -lah .ccache
+  #   - name: Build
+  #     run: sudo ./build.sh
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: debs
+  #       path: deploy/*.deb
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: images
+  #       path: deploy/*.zip
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: packages-info
+  #       path: deploy/*.info
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: mixxx-version
+  #       path: deploy/*.version
   build:
     runs-on: ubuntu-24.04-arm
     steps:
